import { Box, Container, Typography, Paper, Divider } from '@mui/material';

export default function Terms() {
  return (
    <Container maxWidth="md" sx={{ py: { xs: 4, md: 8 } }}>
      <Paper elevation={1} sx={{ p: { xs: 3, md: 5 } }}>
        <Typography variant="h3" component="h1" gutterBottom fontWeight={700}>
          Terms of Service
        </Typography>
        <Typography variant="body2" color="text.secondary" gutterBottom>
          Last updated: October 19, 2025
        </Typography>

        <Divider sx={{ my: 3 }} />

        <Box sx={{ '& > *': { mb: 3 } }}>
          <Box>
            <Typography variant="h5" gutterBottom fontWeight={600}>
              1. Acceptance of Terms
            </Typography>
            <Typography variant="body1" paragraph>
              By accessing and using Explained in 60 seconds ("the Service"), you accept and agree to
              be bound by the terms and provision of this agreement. If you do not agree to these
              terms, please do not use the Service.
            </Typography>
          </Box>

          <Box>
            <Typography variant="h5" gutterBottom fontWeight={600}>
              2. Use License
            </Typography>
            <Typography variant="body1" paragraph>
              We grant you a limited, non-exclusive, non-transferable license to access and use the
              Service for your personal, non-commercial use. This license does not include:
            </Typography>
            <Box component="ul" sx={{ pl: 3 }}>
              <Typography component="li" variant="body1" paragraph>
                Modifying or copying the materials
              </Typography>
              <Typography component="li" variant="body1" paragraph>
                Using the materials for any commercial purpose
              </Typography>
              <Typography component="li" variant="body1" paragraph>
                Attempting to decompile or reverse engineer any software
              </Typography>
              <Typography component="li" variant="body1" paragraph>
                Removing any copyright or proprietary notations
              </Typography>
            </Box>
          </Box>

          <Box>
            <Typography variant="h5" gutterBottom fontWeight={600}>
              3. User Accounts
            </Typography>
            <Typography variant="body1" paragraph>
              When you create an account with us, you must provide accurate and complete information.
              You are responsible for safeguarding your account and for all activities that occur
              under your account.
            </Typography>
          </Box>

          <Box>
            <Typography variant="h5" gutterBottom fontWeight={600}>
              4. Content Generation
            </Typography>
            <Typography variant="body1" paragraph>
              The podcasts generated by our AI service are provided "as is" for informational and
              educational purposes. While we strive for accuracy, we do not guarantee the correctness,
              completeness, or reliability of any generated content.
            </Typography>
          </Box>

          <Box>
            <Typography variant="h5" gutterBottom fontWeight={600}>
              5. Intellectual Property
            </Typography>
            <Typography variant="body1" paragraph>
              The Service and its original content (excluding user-generated content), features, and
              functionality are owned by Explained in 60 seconds and are protected by international
              copyright, trademark, and other intellectual property laws.
            </Typography>
          </Box>

          <Box>
            <Typography variant="h5" gutterBottom fontWeight={600}>
              6. User-Generated Content
            </Typography>
            <Typography variant="body1" paragraph>
              You retain ownership of any content you create using our Service. By using the Service,
              you grant us a worldwide, non-exclusive, royalty-free license to use, reproduce, and
              display your generated content for the purpose of operating and improving the Service.
            </Typography>
          </Box>

          <Box>
            <Typography variant="h5" gutterBottom fontWeight={600}>
              7. Prohibited Uses
            </Typography>
            <Typography variant="body1" paragraph>
              You may not use the Service:
            </Typography>
            <Box component="ul" sx={{ pl: 3 }}>
              <Typography component="li" variant="body1" paragraph>
                For any unlawful purpose
              </Typography>
              <Typography component="li" variant="body1" paragraph>
                To generate content that is harmful, offensive, or violates others' rights
              </Typography>
              <Typography component="li" variant="body1" paragraph>
                To spam or send unsolicited messages
              </Typography>
              <Typography component="li" variant="body1" paragraph>
                To impersonate or attempt to impersonate others
              </Typography>
            </Box>
          </Box>

          <Box>
            <Typography variant="h5" gutterBottom fontWeight={600}>
              8. Disclaimer
            </Typography>
            <Typography variant="body1" paragraph>
              The Service is provided "as is" without warranties of any kind, either express or
              implied. We do not warrant that the Service will be uninterrupted, secure, or error-free.
            </Typography>
          </Box>

          <Box>
            <Typography variant="h5" gutterBottom fontWeight={600}>
              9. Limitation of Liability
            </Typography>
            <Typography variant="body1" paragraph>
              In no event shall Explained in 60 seconds be liable for any indirect, incidental,
              special, consequential, or punitive damages arising out of or relating to your use of
              the Service.
            </Typography>
          </Box>

          <Box>
            <Typography variant="h5" gutterBottom fontWeight={600}>
              10. Changes to Terms
            </Typography>
            <Typography variant="body1" paragraph>
              We reserve the right to modify or replace these Terms at any time. We will provide
              notice of any significant changes by posting the new Terms on this page.
            </Typography>
          </Box>

          <Box>
            <Typography variant="h5" gutterBottom fontWeight={600}>
              11. Contact Information
            </Typography>
            <Typography variant="body1" paragraph>
              If you have any questions about these Terms, please contact us at:
            </Typography>
            <Typography variant="body1" paragraph>
              Email: legal@explainedin60sec.com
            </Typography>
          </Box>
        </Box>
      </Paper>
    </Container>
  );
}

